#!/usr/bin/python3
import sys
import os
import csv
import clingo

# Define the datasets to process automatically
DATASETS = ["training", "ijcai"]

class GeneralFeatureObserver(clingo.backend.Observer):
    """
    Observer that intercepts the ground program generated by Clingo
    to count rules, atoms, and their characteristics.
    """
    def __init__(self):
        self.r = 0              # Total number of rules
        self.atoms = set()      # Set to count unique atoms (a)
        
        self.facts = 0          # Facts
        self.constraints = 0    # Constraints (empty head)
        self.normal = 0         # Normal rules (exactly 1 atom in head)
        self.horn = 0           # Horn rules (no negations in the body)
        
        self.unary = 0          # Unary rules
        self.binary = 0         # Binary rules
        self.ternary = 0        # Ternary rules

    def rule(self, choice, head, body):
        self.r += 1
        for lit in head: self.atoms.add(abs(lit))
        for lit in body: self.atoms.add(abs(lit))
        
        b_len = len(body)
        if b_len == 0: self.facts += 1
        elif b_len == 1: self.unary += 1
        elif b_len == 2: self.binary += 1
        elif b_len == 3: self.ternary += 1
            
        if len(head) == 0:
            self.constraints += 1
            
        if len(head) == 1 and not choice:
            self.normal += 1
            
        has_negation = any(lit < 0 for lit in body)
        if len(head) <= 1 and not choice and not has_negation:
            self.horn += 1

    def weight_rule(self, choice, head, lower_bound, body):
        self.r += 1
        for lit in head: self.atoms.add(abs(lit))
        for lit, weight in body: self.atoms.add(abs(lit))
        if len(head) == 0:
            self.constraints += 1


def extract_general_features(encoding_file, instance_file):
    """Grounds the program and calculates the mathematical features for a single instance."""
    ctl = clingo.Control()
    
    ctl.load(encoding_file)
    ctl.load(instance_file)
    
    obs = GeneralFeatureObserver()
    ctl.register_observer(obs)
    
    ctl.ground([("base", [])])
    
    r = obs.r
    a = len(obs.atoms)
    
    r_safe = r if r > 0 else 1
    a_safe = a if a > 0 else 1
    
    features = {
        "r": r,
        "a": a,
        "r_a": round(r / a_safe, 6), # rules/atoms ratio
        "r_a_2": round((r / a_safe)**2, 6),
        "r_a_3": round((r / a_safe)**3, 6),
        "a_r": round(a / r_safe, 6), # reciprocals
        "a_r_2": round((a / r_safe)**2, 6),
        "a_r_3": round((a / r_safe)**3, 6),
        "f1": round(obs.unary / r_safe, 6), # fraction of unary rules
        "f2": round(obs.binary / r_safe, 6), # fraction of binary rules
        "f3": round(obs.ternary / r_safe, 6), # fraction of ternary rules
        "f_horn": round(obs.horn / r_safe, 6), # fraction of Horn rules
        "n_facts": obs.facts, # number of facts (not normalized, can be zero)
        "f_normal": round(obs.normal / r_safe, 6),
        "f_constr": round(obs.constraints / r_safe, 6),
        "c_r": round(obs.constraints / r_safe, 6)
    }
    return features


def process_dataset(dataset_name):
    """Processes all domains for a specific dataset (training or ijcai)."""
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    
    # --- CONFIGURATION OF THE 3 BENCHMARKS ---
    # Define paths dynamically based on the dataset name
    benchmarks = {
        "GraphColouring": {
            "instances_dir": os.path.join(BASE_DIR, f"../GraphColouring/{dataset_name}-instances-gc"),
            "encoding": os.path.join(BASE_DIR, "../GraphColouring/encoding-plain-amo.asp")
        },
        "GroupAssignment": {
            "instances_dir": os.path.join(BASE_DIR, f"../GroupAssignment/{dataset_name}-instances-ga"),
            "encoding": os.path.join(BASE_DIR, "../GroupAssignment/encoding-plain-amo.asp")
        },
        "Knapsack": {
            "instances_dir": os.path.join(BASE_DIR, f"../Knapsack/{dataset_name}-instances-k"),
            "encoding": os.path.join(BASE_DIR, "../Knapsack/encoding-plain-amo.asp")
        }
    }

    # Unified output CSV
    output_csv = os.path.join(BASE_DIR, f"features_all_general_{dataset_name}.csv")

    # 1. Create a dummy instance to extract keys and prepare the CSV header
    dummy_feats = {
        "r":0, "a":0, "r_a":0, "r_a_2":0, "r_a_3":0, "a_r":0, "a_r_2":0, "a_r_3":0,
        "f1":0, "f2":0, "f3":0, "f_horn":0, "n_facts":0, "f_normal":0, "f_constr":0, "c_r":0
    }
    fieldnames = ["domain", "instance_name"] + list(dummy_feats.keys())

    # 2. Open the CSV file and write data as it gets calculated
    with open(output_csv, mode='w', newline='') as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        writer.writeheader()

        # Iterate through the various domains
        for domain, paths in benchmarks.items():
            inst_dir = paths["instances_dir"]
            enc_file = paths["encoding"]

            print(f"\n==================================================")
            print(f"[{dataset_name.upper()}] Starting processing domain: {domain}")
            
            # Security checks for the current domain
            if not os.path.exists(enc_file):
                print(f"   [!] Error: Encoding not found for {domain} -> {enc_file}")
                continue
            if not os.path.exists(inst_dir):
                print(f"   [!] Error: Instances folder not found for {domain} -> {inst_dir}")
                continue

            # Collect .asp files
            instances = sorted([f for f in os.listdir(inst_dir) if f.endswith(".asp")])
            total_instances = len(instances)
            
            if total_instances == 0:
                print(f"   [!] No instances found in {inst_dir}")
                continue

            print(f"   Found {total_instances} instances. Extraction in progress...")

            # Extraction for each instance
            for i, inst_name in enumerate(instances, 1):
                inst_path = os.path.join(inst_dir, inst_name)
                try:
                    # Extract the mathematical features
                    feats = extract_general_features(enc_file, inst_path)
                    
                    # Add metadata before writing the row
                    feats["domain"] = domain
                    feats["instance_name"] = inst_name
                    
                    writer.writerow(feats)
                    
                    # On-screen progress bar
                    sys.stdout.write(f"\r   Processing: {i}/{total_instances} [{inst_name}]")
                    sys.stdout.flush()
                    
                except Exception as e:
                    # If a file is corrupted, print the error and move to the next without blocking
                    print(f"\n   [!] Error during processing of {inst_name}: {e}")

            # Newline after progress bar
            print()

    print(f"\n✅ Batch extraction successfully completed for dataset: {dataset_name.upper()}!")
    print(f"   Unified dataset saved in: {output_csv}\n")


def main():
    print("Starting pipeline...")
    for dataset in DATASETS:
        process_dataset(dataset)
    print("All tasks completed.")

if __name__ == "__main__":
    main()